name: TNP PR Merged

on:
  pull_request:
    branches:
      # - release-*
      - placeholder
    types:
      - closed

jobs:
  filter:
    name: Filter For Only Merged PRs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/bin/filter@master
      with:
        args: "merged true"

  echovars:
    name: echo GA variables
    runs-on: ubuntu-latest
    steps:
    - run: echo $GITHUB_WORKFLOW
    - run: echo $GITHUB_ACTION
    - run: echo $GITHUB_ACTOR
    - run: echo $GITHUB_REPOSITORY
    - run: echo $GITHUB_EVENT_NAME
    - run: echo $GITHUB_EVENT_PATH
    - run: echo $GITHUB_WORKSPACE
    - run: echo $GITHUB_SHA
    - run: echo $GITHUB_REF
    - run: echo $GITHUB_HEAD_REF
    - run: echo $GITHUB_BASE_REF

  # publish: 
  #   name: Publish Commit Package
  #   runs-on: ubuntu-latest
  #   #needs: tests 
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Write NPM Snapshot Version
  #     uses: thefrontside/actions/write-npm-snapshot-version@master
  #   - name: NPM Publish Commit
  #     uses: actions/npm@master
  #     with: 
  #       args: publish --access=public
  #     env:
  #       NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN2 }}