name: CI

on:
  push:
    branches:
      only: /slave/

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo PUSH SLAVE!
