name: on commit tester

on:
  push:
    branches:
    - release-1.0.0

jobs:
  yeah:
    name: pojpojpoj
    runs-on: ubuntu-latest
    steps:
    - uses: minkimcello/georgia/.github/synchronize-npm-tags@release-1.0.0
