name: on commit tester

on:
  push:
    branches:
    - release-1.0.0

jobs:
  name: hello
  runs-on: ubuntu-latest
  steps:
  - uses: minkimcello/georgia/.github/synchronize-with-npm@release-1.0.0
  