name: on commit (for publishing fork pr merges)

on:
  push:
    branches:
      - release-*
      - features-*

jobs:
  echovars:
    name: echo GA variables
    runs-on: ubuntu-latest
    steps:
    - run: echo $GITHUB_WORKFLOW
    - run: echo $GITHUB_ACTION
    - run: echo $GITHUB_ACTOR
    - run: echo $GITHUB_REPOSITORY
    - run: echo $GITHUB_EVENT_NAME
    - run: echo $GITHUB_EVENT_PATH
    - run: echo $GITHUB_WORKSPACE
    - run: echo $GITHUB_SHA
    - run: echo $GITHUB_REF
    - run: echo $GITHUB_HEAD_REF
    - run: echo $GITHUB_BASE_REF

  filter:
    name: Fork Filter
    runs-on: ubuntu-latest
    steps:
    - name: forking filter
      uses: taras/georgia/.github/actions/filter-for-fork@release-x
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  seepayload:
    name: github payload of merge from a fork
    runs-on: ubuntu-latest
    steps:
    - uses: actions/hello-world-javascript-action@master