name: on commit (for publishing fork pr merges)

on:
  push:
    branches:
      - release-*
      - features-*

jobs:
  echovars:
    name: echo GA variables
    runs-on: ubuntu-latest
    steps:
    - run: echo $GITHUB_WORKFLOW
    - run: echo $GITHUB_ACTION
    - run: echo $GITHUB_ACTOR
    - run: echo $GITHUB_REPOSITORY
    - run: echo $GITHUB_EVENT_NAME
    - run: echo $GITHUB_EVENT_PATH
    - run: echo $GITHUB_WORKSPACE
    - run: echo $GITHUB_SHA
    - run: echo $GITHUB_REF
    - run: echo $GITHUB_HEAD_REF
    - run: echo $GITHUB_BASE_REF
  seepayload:
    name: github payload of merge from a fork
    runs-on: ubuntu-latest
    steps:
    - uses: actions/hello-world-javascript-action@master
    - run: if [[ "${#NPM_AUTH_TOKEN}" -eq "0" ]]; then echo no token; else echo yes token; fi;
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}