name: on push test

on:
  push:
    branches:
    #- release-1.0.0
    - release-x

jobs:
  onpush:
    name: on push tester
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: georgia/future-refactor test
      uses: minkimcello/georgia/.github/false-negative@release-x
      env:
        #NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        NPM_PUBLISH: abc:ding