name: on pr test

on:
  pull_request:
    branches:
      # - features-*
      # - release-*
      - release-*

jobs:
  publish: 
    name: Publish Commit Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: georgia/future-refactor test
      uses: minkimcello/georgia/.github/publish-pr-preview@mk/one_two__yeah
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_TESTER_UMARU }}