name: refactored action tester

on:
  pull_request:
    branches:
      # - features-*
      # - release-*
      - release-*

jobs:
  publish: 
    name: refactored action tester
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: refactored action tester
      uses: minkimcello/actions/publish-pr-preview@mk/reorganize-pr-publish
      with:
        NPM_PUBLISH: npm run abc:ding
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#
