name: on pr

on:
  pull_request:
    branches:
      # - features-*
      # - release-*
      - release-*
      - gitreg

jobs:
  publish: 
    name: on pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: on pr
      uses: minkimcello/georgia/.github/commenter@gitreg
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
