name: TNP Pull Requests

on:
  pull_request:
    branches:
    - release-*

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yarn
      run: yarn
    - name: test
      run: yarn test
    # - name: lint
    #   run: yarn lint
    # - name: coverage
    #   run: |
    #     yarn coverage
    #     yarn coveralls

  publish:
    name: Publish Commit Package
    runs-on: ubuntu-latest
    #needs: tests
    steps:
    - uses: actions/checkout@master
    - name: Update Package Version with Commit SHA
      uses: taras/georgia/.github/actions/sha-version@release-1.0.0
    - name: Try Commenting on PR
      uses: minkimcello/pr-commenter@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Publish Commit
    #   uses: actions/npm@master
    #   with:
    #     args: publish --access=public
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


  # ~~~~~~~~~~~~~~ # ~~~~~~~~~~~~~~ # ~~~~~~~~~~~~~~  examples2
  # ~~~~~~~~~~~~~~ local./
  # danger: 
  #   name: Danger JS
  #   runs-on: ubuntu-latest
  #   needs: publish
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Danger
  #     run: |
  #       # cd .github (update dangerfile to cd up one more)
  #       yarn global add danger --dev
  #       export PATH="$(yarn global bin):$PATH"
  #       danger ci
  #     env: 
  #       #GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB }} # our own bot
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # github action bot

  ## ~~~~~~~~~~~~~~ from repo.
  # danger:
  #   name: Danger JS
  #   needs: publish
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Danger
  #     uses: taras/georgia/.github/actions/Danger@features
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  ## ~~~~~~~~~~~~~~ from source
  # danger:
  #   name: Danger JS
  #   runs-on: ubuntu-latest
  #   needs: publish
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Danger
  #     uses: danger/danger-js@master
  #     #uses: taras/georgia/.github/actions/Danger@features
  #     env: 
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}