name: TNP Pull Requests

on:
  pull_request:
    branches:
    - release-*

jobs:
  npm:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Beta Publish
      uses: actions/npm@master
      with:
        args: version "`node -e \"console.log(require('./package.json').version)\"`-`git log --pretty=format:'%h' -n 1 --skip 1`" --no-git-tag-version && npm publish --access=public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    needs: npm
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Danger
      run: |
        cd .github
        npm install -g yarn
        yarn global add danger --dev
        export PATH="$(yarn global bin):$PATH"
        danger ci
      env: 
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB }}

        ## checking if this works