name: TNP PR Created

on:
  pull_request:
    branches:
      - release-*

jobs:
  # tests:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: yarn
  #     run: yarn 
  #   - name: tests
  #     run: yarn test
  echo:
    name: echoit
    runs-on: ubuntu-latest
    steps:
    - run: echo $GITHUB_ACTOR
    - echo: echo ${{ secrets.YEAH_TOKEN }}

  # publish: 
  #   name: Publish Commit Package
  #   runs-on: ubuntu-latest
  #   #needs: tests 
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Write NPM Snapshot Version
  #     uses: thefrontside/actions/write-npm-snapshot-version@master
  #   - name: NPM Publish Commit
  #     uses: actions/npm@master
  #     with: 
  #       args: publish --access=public
  #     env:
  #       NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # danger: 
  #   name: Danger JS
  #   runs-on: ubuntu-latest
  #   # needs: publish
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Danger Action Test
  #     uses: minkimcello/actions/post-instruction-comment@mk/post-instruction-comment
  #     env: 
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}