name: TNP PR Merged

on:
  pull_request:
    branches:
      - release-*
    types:
      - closed

jobs:
  filter:
    name: Filter For Only Merged PRs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/bin/filter@master
      with:
        args: "merged true"

  publish: 
    name: Publish Commit Package
    runs-on: ubuntu-latest
    #needs: tests 
    steps:
    - uses: actions/checkout@v1
    - name: Write NPM Snapshot Version
      uses: thefrontside/actions/write-npm-snapshot-version@master
    - name: NPM Publish Commit
      uses: actions/npm@master
      with: 
        args: publish --access=public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN2 }}