name: TNP Merge

on:
  push:
    branches:
      - release-*
      
jobs:
  # tests:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: yarn
  #     run: yarn
  #   - name: test
  #     run: yarn test
    # - name: lint
    #   run: yarn lint
    # - name: coverage
    #   run: |
    #     yarn coverage
         # yarn coveralls
            # returning an error currentlys

  publish:
    name: Commit & Publish (not yet really)
    runs-on: ubuntu-latest
    #needs: tests
    steps:
    - uses: actions/checkout@v1
    # ~~~~~~~~~~~~ works! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: Filter by Commit Message
      uses: taras/georgia/.github/actions/filter-by-commit@release-1.0.0
      with:
        filter: skip-actions
    - name: list labels of last merged pr
      uses: minkimcello/js-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.MK_TOKEN }}
    - name: npm version
      uses: actions/npm@master
      with:
        args: version $NPM_VERSION --no-git-tag-version
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
    - name: push package.json to repo manually
      uses: taras/georgia/.github/actions/git-push@release-1.0.0
      with:
        add: package.json
      env:
        GITHUB_TOKEN: ${{ secrets.MK_TOKEN }}

    # - name: publish
    #   uses: actions/npm@master
    #   with:
    #     args: publish --access=public
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}