name: TNP Merge

on:
  push:
    branches:
      - release-*
    

jobs:
  hub:
    name: Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: declare
      run: |
        if [[ "$(git log -1 --pretty=%B)" =~ "[skip-ci]" ]]; then echo skipping; else wget https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz && tar -zxvf hub-linux-amd64-2.12.3.tgz && cd hub-linux-amd64-2.12.3 && sudo ./install && labels=$(hub pr list -s merged -L 1 -f %L) && if [[ "$labels" =~ "bug" ]]; then echo "there is a bug"; else echo "there are no bugs"; fi; fi;
      env:
        GITHUB_TOKEN: ${{secrets.DANGER_GITHUB}}