name: TNP PR Merged

on:
  pull_request:
    branches:
    - release-*
    types:
    - closed

# second commit

jobs:
  filter:
    name: filter ###!
    runs-on: ubuntu-latest
    steps:
    - uses: actions/bin/filter@master
      with:
        args: "merged true"

  commit:
    name: commit ###!
    runs-on: ubuntu-latest
    needs: filter
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.base_ref }}

    - name: list labels of last merged pr ###!
      uses: minkimcello/js-action@master
      id: pr-labels ###!
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: filter separately (beta) ###!
      uses: minkimcello/label-sorter@master
      id: filter-labels  ###!
      with:
        LABELS: ${{ steps.pr-labels.outputs.labels }}
    
    - name: npm version using label variable set from previous step ###!
      uses: actions/npm@master
      with:
        args: version $NPM_VERSION --no-git-tag-version

    - name: commit and push to repo ###!
      uses: taras/georgia/.github/actions/git-push@release-1.0.0
      with:
        add: package.json ###!
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: publish ###!
      uses: actions/npm@master
      with:
        args: publish --access=public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}