name: TNP PR Merged

on:
  pull_request:
    branches:
      - release-*
    types:
      - closed

jobs:
  filter:
    name: Filter For Only Merged PRs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/bin/filter@master
      with:
        args: "merged true"

  commit-publish:
    name: Commit and Publish
    runs-on: ubuntu-latest
    needs: filter
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.base_ref }}

    - name: Fetch Pull Request Labels
      uses: thefrontside/actions/fetch-pull-request-labels@master
      id: pr-labels
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compute Major Minor or Patch
      uses: thefrontside/actions/compute-major-minor-or-patch@master
      with:
        PR_LABELS: ${{ steps.pr-labels.outputs.PR_LABELS }}
    
    - name: NPM Version
      uses: actions/npm@master
      with:
        args: version $MAJOR_OR_MINOR_OR_PATCH --no-git-tag-version 

    - name: Commit Push and Tag Release
      uses: thefrontside/actions/commit-push-and-tag-release@master
      with:
        add: package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: publish
      uses: actions/npm@master
      with:
        args: publish --access=public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      # Would be nice to put this in a separate workflow but github actions seems to not trigger workflows from commits that are triggered within another workflow.
    
