name: TNP Merge

on:
  push:
    branches:
    - release-*

jobs:
  skip:
    name: filter by commit
    runs-on: ubuntu-latest
    steps:
    - name: Filter by Commit Message
      uses: taras/georgia/.github/actions/filter-by-commit@release-1.0.0
      with:
        filter: /#(\d+)/

  # publish:
  #   name: Commit & Publish
  #   runs-on: ubuntu-latest
  #   # needs: skip
  #   steps:
  #   - uses: actions/checkout@v1

  #   - name: list labels of last merged pr
  #     uses: minkimcello/js-action@master
  #     id: pr-labels
  #     with:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: filter separately (beta)
    #   uses: minkimcello/label-sorter@master
    #   id: filter-labels
    #   with:
    #     LABELS: ${{ steps.pr-labels.outputs.labels }}
    
    # - name: npm version using label variable set from previous step
    #   uses: actions/npm@master
    #   with:
    #     args: version $NPM_VERSION --no-git-tag-version

    # - name: commit and push to repo
    #   uses: taras/georgia/.github/actions/git-push@release-1.0.0
    #   with:
    #     add: package.json
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: publish
    #   uses: actions/npm@master
    #   with:
    #     args: publish --access=public
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}