name: TNP Merge

on:
  push:
    branches:
      - release-*
    

jobs:
  hub:
    name: Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # - name: Hub It Up
    #   run: |
    #     if [[ "$(git log -1 --pretty=%B)" =~ "[skip-ci]" ]]
    #     then 
    #       echo skipping
    #     else 
    #       wget https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz
    #       tar -zxvf hub-linux-amd64-2.12.3.tgz
    #       cd hub-linux-amd64-2.12.3
    #       sudo ./install
    #       labels=$(hub pr list -s merged -L 1 -f %L)
    #       if [[ "$labels" =~ "bug" ]]
    #       then 
    #         echo "there is a bug"
    #       else 
    #         echo "there are no bugs"
    #       fi
    #     fi
    #   env:
    #     GITHUB_TOKEN: ${{secrets.DANGER_GITHUB}}
    - name: package bumper
      run: |
        npm version minor --no-git-tag-version
        echo "`node -e \"console.log(require('./package.json').version)\"`"
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Auto-Commit
      # uses: "./.github/auto-commit"
      # with:
      #   args: "waoiejdfoij"
      run: |
        if [[ "$(git log -1 --pretty=%B)" =~ "[skip-ci]" ]]
        then 
          echo skipping
        else 
          echo yeah > yeah.md
          git remote set-url origin https://${GITHUB_TOKEN}:x-oauth-basic@github.com/taras/georgia.git
          git config user.email "minkimcello@gmail.com"
          git config user.name "Min Kim"
          git add yeah.md
          git commit -m "[skip-ci]"
          git push origin refs/heads/release-1.0.0
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.MK_TOKEN }}