name: TNP Merge

on:
  push:
    branches:
      - release-*

jobs:
  hub:
    name: Hub
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v1
    - name: declare
      run: yeah=1 && echo $yeah > test && echo "$(test)"
    - name: persist
      run: echo "$(test)"
    # - name: install
    #   run: wget https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz && tar -zxvf hub-linux-amd64-2.12.3.tgz && cd hub-linux-amd64-2.12.3 && sudo ./install && echo $(hub pr list -s merged -L 1 -f %L)
    #   env:
    #     GITHUB_TOKEN: ${{secrets.DANGER_GITHUB}}