name: TNP PR Merged

on:
  # push:
  pull_request:
    branches:
    - release-*
    types:
    - closed

jobs:
  # filter:
  #   name: filter by commit ###!
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Filter by Commit Message ###! 
  #     uses: taras/georgia/.github/actions/filter-by-commit@release-1.0.0
  #     # with:
  #     #   filter: /#(\d+)/ 
  #   - run: echo $GITHUB_EVENT_NAME

  # filter:
  #   name: filter ###!
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/bin/filter@master
  #     with:
  #       args: "merged true"

  commit:
    name: commit ###!
    runs-on: ubuntu-latest
    # needs: filter
    steps:
    # - uses: minkimcello/script-detector@master
    - name: ECHO VAR
      run: |
        echo REF $GITHUB_REF
        echo BASE_REF $GITHUB_BASE_REF
        echo HEAD_REF $GITHUB_HEAD_REF
        echo WORKFLOW $GITHUB_WORKFLOW 
        echo ACTION $GITHUB_ACTION 
        echo EVENT_NAME $GITHUB_EVENT_NAME 
        echo EVENT_PATH $GITHUB_EVENT_PATH 
        echo WORKSPACE $GITHUB_WORKSPACE 
        echo SHA $GITHUB_SHA
    # - uses: actions/checkout@v1
    #   with:
    #     # ref: $GITHUB_REF/([merge]+)/gi/commit/$GITHUB_SHA
    #     ref: ${{ GITHUB_SHA }}
    - name: list labels of last merged pr ###!
      uses: minkimcello/js-action@master
      id: pr-labels ###!
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: filter separately (beta) ###!
    #   uses: minkimcello/label-sorter@master
    #   id: filter-labels  ###!
    #   with:
    #     LABELS: ${{ steps.pr-labels.outputs.labels }}
    
    # - name: npm version using label variable set from previous step ###!
    #   uses: actions/npm@master
    #   with:
    #     args: version $NPM_VERSION --no-git-tag-version

    # - name: commit and push to repo ###!
    #   uses: taras/georgia/.github/actions/git-push@release-1.0.0
    #   with:
    #     add: package.json ###!
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: publish ###!
    #   uses: actions/npm@master
    #   with:
    #     args: publish --access=public
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}