name: CI2

on:
  pull_request:
    branches:
    - master

jobs:
  npm:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/npm@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Beta Publish
      run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc && npm version "`node -e \"console.log(require('./package.json').version)\"`-`git rev-parse --short HEAD`" --no-git-tag-version
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        args: publish --access public

  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    needs: npm
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Danger
      run: cd .github && npm install -g yarn && yarn global add danger --dev && export PATH="$(yarn global bin):$PATH" && danger ci
      env: 
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB }}