name: CI2

on:
  pull_request:
    branches:
    - master

jobs:
  # build:
  #   name: build and echo
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Run a one-line script
  #     run: echo PULL REQUEST YO 2

  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - name: Danger
      uses: actions/checkout@v1
      uses: danger/danger-js@9.1.6
      env: 
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB }}