name: TNP PR Publish

on:
  push:
    branches:
    - release-*

#second

jobs:
  # filter:
  #   name: filter ###!
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/bin/filter@master
  #     with:
  #       args: "merged true"

  publish:
    name: publish ###!
    runs-on: ubuntu-latest
    # needs: filter
    steps:
    - name: publish ###!
      uses: actions/npm@master
      with:
        args: publish --access=public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}