name: Publish Preview

on:
  pull_request:
    branches:
      - features-*
      - release-*

jobs:
  publish: 
    name: Publish Commit Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo hello
    # - name: string compare
    #   uses: minkimcello/georgia/.github/test-action@features-2
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    # - name: test action
    #   uses: minkimcello/georgia/.github/future-preview-refactor@features-2
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}