name: TNP PR Merged

on:
  pull_request:
    branches:
      - features-*
      - release-*
    types:
      - closed

jobs:
  echovars:
    name: echo GA variables
    runs-on: ubuntu-latest
    steps:
    - run: echo $GITHUB_WORKFLOW
    - run: echo $GITHUB_ACTION
    - run: echo $GITHUB_ACTOR
    - run: echo $GITHUB_REPOSITORY
    - run: echo $GITHUB_EVENT_NAME
    - run: echo $GITHUB_EVENT_PATH
    - run: echo $GITHUB_WORKSPACE
    - run: echo $GITHUB_SHA
    - run: echo $GITHUB_REF
    - run: echo $GITHUB_HEAD_REF
    - run: echo $GITHUB_BASE_REF

  untag:
    name: untag tag
    runs-on: ubuntu-latest
    steps:
    - name: NPM unttagging
      uses: actions/npm@master
      with: 
        args: npm dist-tag rm @minkimcello/npm-tagging features-2
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}