name: Dynamic Testing

on:
  push:
    branches:
      - release-*

jobs:
  test:
    name: test em man
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: json checker
      uses: minkimcello/script-detector@master  